sudo: required
services:
  - docker

before_install:
  - docker build -t sujay/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sujay/react-test npm test --coverage

after_success:
  - docker build -t sujay/multi-client ./client
  - docker build -t sujay/multi-nginx ./nginx
  - docker build -t sujay/multi-server ./server
  - docker build -t sujay/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take and push them to docker cli
  - docker push sujay/multi-client
  - docker push sujay/multi-nginx
  - docker push sujay/multi-server
  - docker push sujay/multi-worker
